#!/bin/sh

## vim: set syntax=sh:
## n - Script to turn on/off an external monitor using XRandR

XRANDR=$(which xrandr)
MAIN=${MAIN:-eDP-1}
SECONDARY=$(xrandr | grep HDMI | grep ' connected' | awk '{print $1}' | head -n1 | tr -d '\n')

#DEFAULT_MODE=1920x1080
DEFAULT_MODE=2560x1440

## args
ORIENTATION="${ORIENTATION:-${3:-'right-of'}}"
MODE="${MODE:-$DEFAULT_MODE}"

if [ "$MODE" = "default" ] || [ "$MODE" = "auto" ]; then
 MODE="$DEFAULT_MODE"
fi

## stupid hack for xrandr
DISPLAY=":0.0"
export DISPLAY

on() {
  local primary="$1"
  local secondary="$2"
  local mode="$3"
  $XRANDR --output $primary --primary --output $secondary --right-of $primary --mode $mode --scale 1.5x1.5
}

off() {
  local target=$1
  $XRANDR --output $target --off
}

## determine arguments
case "$1" in
  on) on $MAIN $SECONDARY $MODE ;;
  off) off $SECONDARY ;;
  status) $XRANDR ;;

  switch)
    # grab current state of extrnal monitor
    state=$($XRANDR | grep $SECONDARY | cut -f 2 -d' ')
    if [[ $state == "connected" ]]; then
      on $SECONDARY $MAIN $MODE
    else
      off $SECONDARY
    fi
  ;;

  *)
  echo "Usage: extmon [on|off|switch]"
  ;;
esac
