#!/bin/sh

## vim: set syntax=sh:
## n - Script to turn on/off an external monitor using XRandR

XRANDR=$(which xrandr)
MAIN=${MAIN:-eDP-1}
SECONDARY=$(xrandr | grep HDMI | grep ' connected' | awk '{print $1}' | head -n1 | tr -d '\n')

#DEFAULT_MODE=1920x1080
#DEFAULT_MODE=2560x1440
DEFAULT_MODE=3840x2160

## args
ORIENTATION="${ORIENTATION:-${3:-above}}"
MODE="${MODE:-$DEFAULT_MODE}"

if [ "$MODE" = "default" ] || [ "$MODE" = "auto" ]; then
 MODE="$DEFAULT_MODE"
fi

## stupid hack for xrandr
DISPLAY=":0.0"
export DISPLAY

on() {
  local primary="$1"; shift
  local secondary="$1"; shift
  local mode="$1"; shift
  #echo \
  $XRANDR --output $primary --primary --auto --output $secondary --auto --$ORIENTATION $primary --mode $mode $@
}

off() {
  local target="$1"
  #echo \
  $XRANDR --output $target --off
}

arg="$1"; shift
## determine arguments
case "$arg" in
  on) on $MAIN $SECONDARY $MODE $@;;
  off) off $SECONDARY $@;;
  status) $XRANDR ;;

  switch)
    # grab current state of extrnal monitor
    state=$($XRANDR | grep $SECONDARY | cut -f 2 -d' ')
    if [[ $state == "connected" ]]; then
      on $SECONDARY $MAIN $MODE
    else
      off $SECONDARY
    fi
  ;;

  *)
  echo "Usage: extmon [on|off|switch]"
  ;;
esac
