#!/bin/bash

token="$(echo $1 | tr '[:lower:]' '[:upper:]')"

case "$token" in
  BTC)
    VALUE=$(curl -s 'https://blockchain.info/ticker'|jq '.["USD"]["15m"]' || echo '…')
    VALUE=$(bc <<< "scale=3; $(echo $VALUE)")
    ;;

  *)
    VALUE=$(curl -s 'https://poloniex.com/public?command=returnTicker'|jq ".USDT_$token.last"| sed -e 's/^"//'  -e 's/"$//' || echo '0')
    VALUE=$(bc <<< "scale=1; $(echo $VALUE)")
    ;;

esac

echo $VALUE | sed -e 's/^\./0./'
