#!/bin/bash
check() {
  pac=$(checkupdates | wc -l)
  if (( $? != 0 )); then echo "(?)"; return 1; fi
  aur=$(cower -u | wc -l)
  if (( $? != 0 )); then echo "(?)"; return 1; fi

  check=$((pac + aur))
  if [[ "$check" != "0" ]]; then
    echo "$pac %{F#6b5b5b}%{F-} $aur"
  else
    echo "No updates available."
  fi
}

check
