#!/bin/sh

## destroy running polybars
killall polybar
killall polybar

## timeout until started
sleep 2

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	export MONITOR="$m"
	echo $MONITOR
	polybar top -c ~/.polybar &
	polybar bottom -c ~/.polybar &
done
