#!/bin/sh

killall polybar
polybar top -c ~/.polybar &
polybar bottom -c ~/.polybar &

if ! [ -z "$(xrandr | grep HDMI | grep ' connected' | awk '{print $1}' | head -n1 | tr -d '\n')" ]; then
  echo "secondary"
  polybar top-secondary -c ~/.polybar &
fi
